### ISSUE TITLE
SQL Injection Vulnerability in complete.php

### ISSUE THREAD

**Issue by HenryHoggard** [cyberhorse/SPHP#1]
File: complete.php
https://github.com/cyberhorse/SPHP/blob/081769dc0db172f632a85483cc1c44fe993d2b2f/blog/complete.php
Needs sanitization on SQL query  "where user = $_GET"
 See http://php.net/manual/en/security.database.sql-injection.php

**Comment by ipeevski** [comment]
Fixed
